// Generated by scripts/optimize-site-images.mjs; original sources are preserved in its manifest.
export const heroImages = [
  {
    "src": "/media/web/hero-01-384.webp",
    "srcSet": "/media/web/hero-01-192.webp 192w, /media/web/hero-01-384.webp 384w",
    "width": 736,
    "height": 1200
  },
  {
    "src": "/media/web/hero-02-384.webp",
    "srcSet": "/media/web/hero-02-192.webp 192w, /media/web/hero-02-384.webp 384w",
    "width": 1200,
    "height": 970
  },
  {
    "src": "/media/web/hero-03-384.webp",
    "srcSet": "/media/web/hero-03-192.webp 192w, /media/web/hero-03-384.webp 384w",
    "width": 1200,
    "height": 1163
  },
  {
    "src": "/media/web/hero-04-384.webp",
    "srcSet": "/media/web/hero-04-192.webp 192w, /media/web/hero-04-384.webp 384w",
    "width": 803,
    "height": 1200
  },
  {
    "src": "/media/web/hero-05-384.webp",
    "srcSet": "/media/web/hero-05-192.webp 192w, /media/web/hero-05-384.webp 384w",
    "width": 807,
    "height": 1200
  },
  {
    "src": "/media/web/hero-06-384.webp",
    "srcSet": "/media/web/hero-06-192.webp 192w, /media/web/hero-06-384.webp 384w",
    "width": 1041,
    "height": 1200
  },
  {
    "src": "/media/web/hero-07-384.webp",
    "srcSet": "/media/web/hero-07-192.webp 192w, /media/web/hero-07-384.webp 384w",
    "width": 1200,
    "height": 1146
  },
  {
    "src": "/media/web/hero-08-384.webp",
    "srcSet": "/media/web/hero-08-192.webp 192w, /media/web/hero-08-384.webp 384w",
    "width": 962,
    "height": 1200
  },
  {
    "src": "/media/web/hero-09-384.webp",
    "srcSet": "/media/web/hero-09-192.webp 192w, /media/web/hero-09-384.webp 384w",
    "width": 1200,
    "height": 975
  },
  {
    "src": "/media/web/hero-10-384.webp",
    "srcSet": "/media/web/hero-10-192.webp 192w, /media/web/hero-10-384.webp 384w",
    "width": 1200,
    "height": 798
  },
  {
    "src": "/media/web/hero-11-384.webp",
    "srcSet": "/media/web/hero-11-192.webp 192w, /media/web/hero-11-384.webp 384w",
    "width": 1200,
    "height": 1158
  },
  {
    "src": "/media/web/hero-12-384.webp",
    "srcSet": "/media/web/hero-12-192.webp 192w, /media/web/hero-12-384.webp 384w",
    "width": 1135,
    "height": 1200
  },
  {
    "src": "/media/web/hero-13-384.webp",
    "srcSet": "/media/web/hero-13-192.webp 192w, /media/web/hero-13-384.webp 384w",
    "width": 927,
    "height": 1200
  },
  {
    "src": "/media/web/hero-14-384.webp",
    "srcSet": "/media/web/hero-14-192.webp 192w, /media/web/hero-14-384.webp 384w",
    "width": 967,
    "height": 1200
  },
  {
    "src": "/media/web/hero-15-384.webp",
    "srcSet": "/media/web/hero-15-192.webp 192w, /media/web/hero-15-384.webp 384w",
    "width": 1175,
    "height": 1200
  },
  {
    "src": "/media/web/hero-16-384.webp",
    "srcSet": "/media/web/hero-16-192.webp 192w, /media/web/hero-16-384.webp 384w",
    "width": 964,
    "height": 1200
  },
  {
    "src": "/media/web/hero-17-384.webp",
    "srcSet": "/media/web/hero-17-192.webp 192w, /media/web/hero-17-384.webp 384w",
    "width": 1010,
    "height": 1200
  },
  {
    "src": "/media/web/hero-18-384.webp",
    "srcSet": "/media/web/hero-18-192.webp 192w, /media/web/hero-18-384.webp 384w",
    "width": 1200,
    "height": 1119
  },
  {
    "src": "/media/web/hero-19-384.webp",
    "srcSet": "/media/web/hero-19-192.webp 192w, /media/web/hero-19-384.webp 384w",
    "width": 984,
    "height": 1200
  },
  {
    "src": "/media/web/hero-20-384.webp",
    "srcSet": "/media/web/hero-20-192.webp 192w, /media/web/hero-20-384.webp 384w",
    "width": 1200,
    "height": 1189
  },
  {
    "src": "/media/web/hero-21-384.webp",
    "srcSet": "/media/web/hero-21-192.webp 192w, /media/web/hero-21-384.webp 384w",
    "width": 1182,
    "height": 1200
  },
  {
    "src": "/media/web/hero-22-384.webp",
    "srcSet": "/media/web/hero-22-192.webp 192w, /media/web/hero-22-384.webp 384w",
    "width": 1016,
    "height": 1200
  },
  {
    "src": "/media/web/hero-23-384.webp",
    "srcSet": "/media/web/hero-23-192.webp 192w, /media/web/hero-23-384.webp 384w",
    "width": 972,
    "height": 1200
  },
  {
    "src": "/media/web/hero-24-384.webp",
    "srcSet": "/media/web/hero-24-192.webp 192w, /media/web/hero-24-384.webp 384w",
    "width": 1200,
    "height": 798
  },
  {
    "src": "/media/web/hero-25-384.webp",
    "srcSet": "/media/web/hero-25-192.webp 192w, /media/web/hero-25-384.webp 384w",
    "width": 1200,
    "height": 672
  },
  {
    "src": "/media/web/hero-26-384.webp",
    "srcSet": "/media/web/hero-26-192.webp 192w, /media/web/hero-26-384.webp 384w",
    "width": 1200,
    "height": 1064
  },
  {
    "src": "/media/web/hero-27-384.webp",
    "srcSet": "/media/web/hero-27-192.webp 192w, /media/web/hero-27-384.webp 384w",
    "width": 1200,
    "height": 938
  },
  {
    "src": "/media/web/hero-28-384.webp",
    "srcSet": "/media/web/hero-28-192.webp 192w, /media/web/hero-28-384.webp 384w",
    "width": 1200,
    "height": 952
  },
  {
    "src": "/media/web/hero-29-384.webp",
    "srcSet": "/media/web/hero-29-192.webp 192w, /media/web/hero-29-384.webp 384w",
    "width": 1200,
    "height": 969
  },
  {
    "src": "/media/web/hero-30-384.webp",
    "srcSet": "/media/web/hero-30-192.webp 192w, /media/web/hero-30-384.webp 384w",
    "width": 1200,
    "height": 785
  },
  {
    "src": "/media/web/hero-31-384.webp",
    "srcSet": "/media/web/hero-31-192.webp 192w, /media/web/hero-31-384.webp 384w",
    "width": 942,
    "height": 1200
  },
  {
    "src": "/media/web/hero-32-384.webp",
    "srcSet": "/media/web/hero-32-192.webp 192w, /media/web/hero-32-384.webp 384w",
    "width": 1149,
    "height": 1200
  },
  {
    "src": "/media/web/hero-33-384.webp",
    "srcSet": "/media/web/hero-33-192.webp 192w, /media/web/hero-33-384.webp 384w",
    "width": 981,
    "height": 1200
  },
  {
    "src": "/media/web/hero-34-384.webp",
    "srcSet": "/media/web/hero-34-192.webp 192w, /media/web/hero-34-384.webp 384w",
    "width": 989,
    "height": 1200
  },
  {
    "src": "/media/web/hero-35-384.webp",
    "srcSet": "/media/web/hero-35-192.webp 192w, /media/web/hero-35-384.webp 384w",
    "width": 1200,
    "height": 1189
  },
  {
    "src": "/media/web/hero-36-384.webp",
    "srcSet": "/media/web/hero-36-192.webp 192w, /media/web/hero-36-384.webp 384w",
    "width": 1197,
    "height": 1200
  },
  {
    "src": "/media/web/hero-37-384.webp",
    "srcSet": "/media/web/hero-37-192.webp 192w, /media/web/hero-37-384.webp 384w",
    "width": 988,
    "height": 1200
  },
  {
    "src": "/media/web/hero-38-384.webp",
    "srcSet": "/media/web/hero-38-192.webp 192w, /media/web/hero-38-384.webp 384w",
    "width": 1200,
    "height": 790
  },
  {
    "src": "/media/web/hero-39-384.webp",
    "srcSet": "/media/web/hero-39-192.webp 192w, /media/web/hero-39-384.webp 384w",
    "width": 1053,
    "height": 1200
  },
  {
    "src": "/media/web/hero-40-384.webp",
    "srcSet": "/media/web/hero-40-192.webp 192w, /media/web/hero-40-384.webp 384w",
    "width": 1062,
    "height": 1200
  },
  {
    "src": "/media/web/hero-41-384.webp",
    "srcSet": "/media/web/hero-41-192.webp 192w, /media/web/hero-41-384.webp 384w",
    "width": 420,
    "height": 420
  },
  {
    "src": "/media/web/hero-42-384.webp",
    "srcSet": "/media/web/hero-42-192.webp 192w, /media/web/hero-42-384.webp 384w",
    "width": 420,
    "height": 420
  },
  {
    "src": "/media/web/hero-43-384.webp",
    "srcSet": "/media/web/hero-43-192.webp 192w, /media/web/hero-43-384.webp 384w",
    "width": 420,
    "height": 420
  },
  {
    "src": "/media/web/hero-44-384.webp",
    "srcSet": "/media/web/hero-44-192.webp 192w, /media/web/hero-44-384.webp 384w",
    "width": 420,
    "height": 420
  },
  {
    "src": "/media/web/hero-45-384.webp",
    "srcSet": "/media/web/hero-45-192.webp 192w, /media/web/hero-45-384.webp 384w",
    "width": 420,
    "height": 420
  },
  {
    "src": "/media/web/hero-46-384.webp",
    "srcSet": "/media/web/hero-46-192.webp 192w, /media/web/hero-46-384.webp 384w",
    "width": 420,
    "height": 420
  },
  {
    "src": "/media/web/hero-47-384.webp",
    "srcSet": "/media/web/hero-47-192.webp 192w, /media/web/hero-47-384.webp 384w",
    "width": 420,
    "height": 420
  },
  {
    "src": "/media/web/hero-48-384.webp",
    "srcSet": "/media/web/hero-48-192.webp 192w, /media/web/hero-48-384.webp 384w",
    "width": 420,
    "height": 420
  },
  {
    "src": "/media/web/hero-49-384.webp",
    "srcSet": "/media/web/hero-49-192.webp 192w, /media/web/hero-49-384.webp 384w",
    "width": 420,
    "height": 420
  },
  {
    "src": "/media/web/hero-50-384.webp",
    "srcSet": "/media/web/hero-50-192.webp 192w, /media/web/hero-50-384.webp 384w",
    "width": 420,
    "height": 420
  },
  {
    "src": "/media/web/hero-51-384.webp",
    "srcSet": "/media/web/hero-51-192.webp 192w, /media/web/hero-51-384.webp 315w",
    "width": 315,
    "height": 560
  },
  {
    "src": "/media/web/hero-52-384.webp",
    "srcSet": "/media/web/hero-52-192.webp 192w, /media/web/hero-52-384.webp 315w",
    "width": 315,
    "height": 560
  },
  {
    "src": "/media/web/hero-53-384.webp",
    "srcSet": "/media/web/hero-53-192.webp 192w, /media/web/hero-53-384.webp 384w",
    "width": 420,
    "height": 525
  },
  {
    "src": "/media/web/hero-54-384.webp",
    "srcSet": "/media/web/hero-54-192.webp 192w, /media/web/hero-54-384.webp 384w",
    "width": 420,
    "height": 560
  },
  {
    "src": "/media/web/hero-55-384.webp",
    "srcSet": "/media/web/hero-55-192.webp 192w, /media/web/hero-55-384.webp 384w",
    "width": 420,
    "height": 525
  },
  {
    "src": "/media/web/hero-56-384.webp",
    "srcSet": "/media/web/hero-56-192.webp 192w, /media/web/hero-56-384.webp 384w",
    "width": 420,
    "height": 525
  },
  {
    "src": "/media/web/hero-57-384.webp",
    "srcSet": "/media/web/hero-57-192.webp 192w, /media/web/hero-57-384.webp 384w",
    "width": 512,
    "height": 640
  },
  {
    "src": "/media/web/hero-58-384.webp",
    "srcSet": "/media/web/hero-58-192.webp 192w, /media/web/hero-58-384.webp 384w",
    "width": 1152,
    "height": 1572
  },
  {
    "src": "/media/web/hero-59-384.webp",
    "srcSet": "/media/web/hero-59-192.webp 192w, /media/web/hero-59-384.webp 384w",
    "width": 2278,
    "height": 1510
  },
  {
    "src": "/media/web/hero-60-384.webp",
    "srcSet": "/media/web/hero-60-192.webp 192w, /media/web/hero-60-384.webp 384w",
    "width": 512,
    "height": 640
  },
  {
    "src": "/media/web/hero-61-384.webp",
    "srcSet": "/media/web/hero-61-192.webp 192w, /media/web/hero-61-384.webp 384w",
    "width": 1144,
    "height": 770
  },
  {
    "src": "/media/web/hero-62-384.webp",
    "srcSet": "/media/web/hero-62-192.webp 192w, /media/web/hero-62-384.webp 384w",
    "width": 512,
    "height": 640
  },
  {
    "src": "/media/web/hero-63-384.webp",
    "srcSet": "/media/web/hero-63-192.webp 192w, /media/web/hero-63-384.webp 384w",
    "width": 1280,
    "height": 1160
  }
] as const;

export const siteImages = {
  "chef-hero-apron": {
    "src": "/media/web/chef-hero-apron-576.webp",
    "srcSet": "/media/web/chef-hero-apron-320.webp 320w, /media/web/chef-hero-apron-576.webp 576w",
    "width": 576,
    "height": 1280
  },
  "masterchef": {
    "src": "/media/web/masterchef-640.webp",
    "srcSet": "/media/web/masterchef-320.webp 320w, /media/web/masterchef-640.webp 640w",
    "width": 1280,
    "height": 1160
  },
  "private-dinner-wide-v2": {
    "src": "/media/web/private-dinner-wide-v2-1536.webp",
    "srcSet": "/media/web/private-dinner-wide-v2-384.webp 384w, /media/web/private-dinner-wide-v2-768.webp 768w, /media/web/private-dinner-wide-v2-1536.webp 1536w",
    "width": 1536,
    "height": 1024
  },
  "private-events": {
    "src": "/media/web/private-events-1536.webp",
    "srcSet": "/media/web/private-events-384.webp 384w, /media/web/private-events-768.webp 768w, /media/web/private-events-1536.webp 1536w",
    "width": 2278,
    "height": 1510
  },
  "masterclasses": {
    "src": "/media/web/masterclasses-1144.jpg",
    "srcSet": "/media/web/masterclasses-384.jpg 384w, /media/web/masterclasses-768.jpg 768w, /media/web/masterclasses-1144.jpg 1144w",
    "width": 1144,
    "height": 770
  },
  "conversation": {
    "src": "/media/web/conversation-guest-2026-09-18-960.webp",
    "srcSet": "/media/web/conversation-guest-2026-09-18-480.webp 480w, /media/web/conversation-guest-2026-09-18-960.webp 960w",
    "width": 1536,
    "height": 1024
  },
  "toast": {
    "src": "/media/web/toast-960.webp",
    "srcSet": "/media/web/toast-480.webp 480w, /media/web/toast-960.webp 960w",
    "width": 1536,
    "height": 1024
  },
  "duck-plate": {
    "src": "/media/web/duck-plate-960.webp",
    "srcSet": "/media/web/duck-plate-480.webp 480w, /media/web/duck-plate-960.webp 960w",
    "width": 1800,
    "height": 1665
  },
  "film-poster": {
    "src": "/media/web/film-poster-540.webp",
    "srcSet": "/media/web/film-poster-540.webp 540w",
    "width": 1080,
    "height": 1920
  },
  "chef-landscape": {
    "src": "/media/web/chef-landscape-2026-09-19-1024.webp",
    "srcSet": "/media/web/chef-landscape-2026-09-19-480.webp 480w, /media/web/chef-landscape-2026-09-19-768.webp 768w, /media/web/chef-landscape-2026-09-19-1024.webp 1024w",
    "width": 1024,
    "height": 1536
  }
} as const;
