// Complete build-time translation of the approved Russian homepage.
export const homeEnglish = {
  "К содержимому": "Skip to content",
  "Форматы": "Formats",
  "О шефе": "About the chef",
  "Продукты": "Ingredients",
  "Как всё проходит": "How it works",
  "Обсудить вечер": "Plan your evening",
  "Персональное меню": "A personal menu",
  "Евгений": "Evgen",
  "Гребеник.": "Grebenik.",
  "Ваш личный мастер-шеф на Кипре": "Your private chef in Cyprus",
  "Частные ужины, приватные мероприятия и мастер-классы на Кипре.": "Private dinners, events and cooking classes in Cyprus.",
  "Обсудить ваш вечер": "Plan your evening",
  "Современная авторская кухня": "Contemporary signature cuisine",
  "Мой опыт —": "My experience —",
  "для вашего вечера.": "for your evening.",
  "Евгений Гребеник · «МастерШеф. Профессионалы»": "Evgen Grebenik · MasterChef: The Professionals",
  "В основе моей кухни — опыт лучших кулинарных школ Франции, Швейцарии и Германии, путь к которым мне открыла победа в «МастерШеф. Профессионалы». Полученные знания я переосмыслил в своей кухне — современной, европейской, с авторским характером.": "My cooking draws on experience at leading culinary schools in France, Switzerland and Germany, an opportunity opened by winning MasterChef: The Professionals. I have made that knowledge my own through contemporary European cooking with a personal character.",
  "Сегодня на Кипре я готовлю для частных ужинов и приватных мероприятий, а на мастер-классах делюсь своим опытом и подходом к приготовлению.": "Today, I cook for private dinners and events in Cyprus, and share my experience and approach to cooking through classes.",
  "Франция · Швейцария · Германия": "France · Switzerland · Germany",
  "лет в гастрономии": "years in gastronomy",
  "лет работы шеф-поваром": "years as a chef",
  "Ваши вкусы": "Your tastes",
  "основа каждого меню": "at the heart of every menu",
  "Готовлю": "Cooking",
  "по всему Кипру для вас": "for you across Cyprus",
  "Какой будет": "What kind of",
  "ваш вечер?": "evening will it be?",
  "Собрать близких, встретиться с друзьями": "Bring loved ones together, meet friends",
  "или приготовить ужин вместе.": "or cook dinner together.",
  "Приватный ужин": "Private dinner",
  "Частные мероприятия": "Private events",
  "Мастер-классы": "Cooking classes",
  "Частный ужин": "Private dinner",
  "Мероприятия": "Events",
  "Ваш вечер. Авторский ужин в 7 подач.": "Your evening. A signature dinner in 7 courses.",
  "Меню составлю по вашим вкусам, приготовление и подачу возьму на себя, а вы сможете насладиться авторским ужином в 7 подач.": "I will create a menu around your tastes, take care of the cooking and serving, and leave you to enjoy a signature dinner in 7 courses.",
  "Обсудить встречу": "Plan your gathering",
  "Подробнее": "Learn more",
  "Приватные мероприятия": "Private events",
  "Главное — быть вместе.": "Time together matters.",
  "Подберу и приготовлю закуски и блюда, которые удобно есть за разговором.": "I will choose and prepare appetisers and dishes that are easy to enjoy while talking.",
  "Понять вкус через практику.": "Explore flavour through practice.",
  "Готовим вместе: я показываю техники и приёмы, объясняю, что они меняют в блюде, и помогаю разобраться в процессах. Затем пробуем приготовленное за общим столом.": "We cook together: I demonstrate techniques, explain how they affect a dish and help you understand the process. Then we taste what we have made around one table.",
  "От разговора — к вашему столу. Как рождается ваш вечер.": "From conversation to your table. How your evening takes shape.",
  "Всё начинается с разговора": "It starts with a conversation",
  "Знакомимся": "Getting to know you",
  "Расскажите, по какому поводу собираетесь. Обсудим любимые блюда и пожелания к меню.": "Tell me about the occasion. We will discuss your favourite dishes and menu preferences.",
  "Можно прийти с готовой идеей. Можно начать с одного пожелания.": "Come with a clear idea, or start with just one preference.",
  "02 · Продумываю меню": "02 · Creating your menu",
  "От пожеланий — к сочетаниям": "From preferences to pairings",
  "Продумываю меню": "Creating your menu",
  "Из ваших пожеланий складывается меню. Я выбираю продукты и продумываю, как они будут сочетаться между собой.": "Your preferences shape the menu. I choose ingredients and consider how their flavours will work together.",
  "03 · Магия начинается с выбора": "03 · It starts with the ingredients",
  "Кипр · Продукты для вашего меню": "Cyprus · Ingredients for your menu",
  "Магия начинается с выбора": "It starts with the ingredients",
  "Выбор продукта — такая же важная часть моей работы, как приготовление. Свежесть и качество мяса, рыбы и морепродуктов задают вкус задолго до того, как я начинаю готовить.": "Choosing ingredients is as important to my work as cooking. The freshness and quality of meat, fish and seafood shape the flavour long before I begin to cook.",
  "Лофу": "Lofou",
  "Мясо": "Meat",
  "За ягнёнком еду в деревню Лофу. Выбираю мясо под блюдо, которое задумал.": "I go to the village of Lofou for lamb, choosing the meat for the dish I have in mind.",
  "Зиги": "Zygi",
  "Рыба и морепродукты": "Fish and seafood",
  "За рыбой и морепродуктами еду в рыбацкую деревню Зиги и выбираю по свежести и качеству.": "I go to the fishing village of Zygi for fish and seafood, choosing for freshness and quality.",
  "Фермы": "Farms",
  "Овощи и фрукты": "Fruit and vegetables",
  "За сезонными овощами и фруктами езжу к фермерам. За спелой клубникой — на клубничную ферму.": "I visit farmers for seasonal fruit and vegetables, and a strawberry farm for ripe strawberries.",
  "Сезонные овощи": "Seasonal vegetables",
  "Начало приготовления": "Cooking begins",
  "04 · Собираю вкус": "04 · Bringing flavours together",
  "Каждый продукт играет свою роль": "Every ingredient plays a part",
  "Собираю вкус": "Bringing flavours together",
  "Сочность, свежесть, сладость и кислинка дополняют друг друга.": "Juiciness, freshness, sweetness and acidity complement each other.",
  "Atlas · Одно блюдо, четыре акцента": "Atlas · One dish, four elements",
  "Утка": "Duck",
  "Сочное мясо и хрустящая кожица.": "Succulent meat and crisp skin.",
  "Овощи и грибы": "Vegetables and mushrooms",
  "Свежесть овощей, насыщенность грибов и хруст чипсов.": "Fresh vegetables, rich mushrooms and the crunch of crisps.",
  "Два пюре": "Two purées",
  "Фенхель даёт нежность, батат — сладость.": "Fennel brings delicacy; sweet potato brings sweetness.",
  "Соус с юдзу": "Yuzu sauce",
  "Объединяет вкусы и добавляет кислинку.": "Brings the flavours together with a touch of acidity.",
  "05 · Подготовку беру на себя": "05 · I take care of preparation",
  "Смотреть видео подготовки": "Watch the preparation video",
  "Работа на кухне · Видео Евгения": "In the kitchen · Video by Evgen",
  "Подготовку беру на себя": "I take care of preparation",
  "Закупаю продукты и начинаю работу на вашей кухне: делаю заготовки, готовлю соусы и маринады. То, что требует времени, готовлю заранее.": "I shop for ingredients and get to work in your kitchen, preparing the food, sauces and marinades. Anything that needs more time is prepared in advance.",
  "Смотреть видео": "Watch the video",
  "Звук": "Sound",
  "вкл.": "on",
  "Открыть видео ↗": "Open video ↗",
  "06 · Этот вечер — ваш": "06 · The evening is yours",
  "Время за вашим столом": "Time around your table",
  "Этот вечер — ваш": "The evening is yours",
  "Вы проводите время с гостями. Я готовлю и подаю блюда.": "You spend time with your guests. I cook and serve the dishes.",
  "Расскажите мне о вечере": "Tell me about your evening",
  "Начнём с вашего «хочу»": "Start with what you have in mind",
  "Обсудим ваш вечер": "Let's plan your evening",
  "Начнём с разговора": "Let's start with a conversation",
  "Обсудим": "Let's plan",
  "ваш вечер.": "your evening.",
  "Напишите мне о поводе, дате и количестве гостей.": "Tell me the occasion, date and number of guests.",
  "Вместе найдём подходящий формат.": "Together, we will find the right format.",
  "Написать в Instagram": "Message on Instagram",
  "Закрыть": "Close",
  "Формат встречи": "Gathering format",
  "Собрать близких за одним столом и спокойно поужинать.": "Bring loved ones around one table for an unhurried dinner.",
  "Вспомним любимые блюда, обсудим, что хочется попробовать и чего точно не должно быть в меню.": "We will talk about your favourite dishes, what you would like to try and what you want to leave off the menu.",
  "Основная навигация": "Main navigation",
  "Евгений Гребеник — к началу": "Evgen Grebenik — back to top",
  "Открыть меню": "Open menu",
  "Мобильная навигация": "Mobile navigation",
  "Евгений Гребеник улыбается, стоя в полосатом поварском фартуке": "Evgen Grebenik smiling in a striped chef's apron",
  "Воспроизвести видео с шефом": "Play the chef video",
  "Евгений Гребеник в поварском кителе с конвертом победителя на «МастерШеф. Профессионалы»": "Evgen Grebenik in a chef's jacket holding the winner's envelope on MasterChef: The Professionals",
  "Опыт и подход": "Experience and approach",
  "Выбор формата": "Choose a format",
  "Показать формат: Частный ужин": "Show format: Private dinner",
  "Показать формат: Мероприятия": "Show format: Events",
  "Показать формат: Мастер-классы": "Show format: Cooking classes",
  "Евгений готовит блюдо на сковороде на профессиональной кухне": "Evgen cooking in a pan in a professional kitchen",
  "Евгений готовит блины на открытом воздухе в белой футболке и чёрном фартуке": "Evgen cooking pancakes outdoors in a white T-shirt and black apron",
  "Участники мастер-класса наблюдают за работой Евгения за общим столом": "Cooking class participants watching Evgen work around a shared table",
  "Евгений общается с гостями за столом на террасе": "Evgen talking with guests around a table on the terrace",
  "Следующий этап: Продумываю меню": "Next step: Creating your menu",
  "Руки листают тетрадь с ингредиентами и кулинарными заметками": "Hands turning the pages of a notebook with ingredients and cooking notes",
  "Следующий этап: Магия начинается с выбора": "Next step: It starts with the ingredients",
  "Утиные грудки, шиитаке, морковь, шалот и травы перед приготовлением": "Duck breasts, shiitake mushrooms, carrots, shallots and herbs before cooking",
  "Грибы шиитаке, овощи и зелень на деревянной доске": "Shiitake mushrooms, vegetables and herbs on a wooden board",
  "Утиную грудку с румяной кожицей переворачивают на сковороде": "A duck breast with golden skin being turned in a pan",
  "Следующий этап: Собираю вкус": "Next step: Bringing flavours together",
  "Блюдо Atlas: утка, овощи и шиитаке, пюре из фенхеля и батата, чипсы и соус с юдзу": "The Atlas dish: duck, vegetables and shiitake mushrooms, fennel and sweet potato purées, crisps and yuzu sauce",
  "Следующий этап: Подготовку беру на себя": "Next step: I take care of preparation",
  "Евгений раскладывает инструменты и делает заготовки на кухне": "Evgen arranging utensils and preparing ingredients in the kitchen",
  "Выключить звук": "Mute",
  "Открыть видео подготовки в отдельной вкладке": "Open the preparation video in a new tab",
  "Следующий этап: Этот вечер — ваш": "Next step: The evening is yours",
  "Иллюстрация: Евгений наливает вино гостю за ужином при свечах на террасе виллы": "Illustration: Evgen pouring wine for a guest at a candlelit dinner on a villa terrace",
  "Перейти к контактам": "Go to contact details",
  "Евгений Гребеник улыбается, стоя со скрещёнными руками на открытой террасе": "Evgen Grebenik smiling with his arms crossed on an open terrace",
  "Закрыть окно": "Close dialog",
  "Русский": "Русский",
  "Все подробности ужина": "Full dinner details"
};
